package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// CreateRightsRequest is the resolver for the createRightsRequest field.
func (r *mutationResolver) CreateRightsRequest(ctx context.Context, input types.CreateRightsRequestInput) (*types.CreateRightsRequestPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionRightsRequestCreate)
	if err != nil {
		return nil, err
	}

	req := probo.CreateRightsRequestRequest{
		OrganizationID: input.OrganizationID,
		RequestType:    &input.RequestType,
		RequestState:   &input.RequestState,
		DataSubject:    input.DataSubject,
		Contact:        input.Contact,
		Details:        input.Details,
		Deadline:       input.Deadline,
		ActionTaken:    input.ActionTaken,
	}

	rightsRequest, err := r.probo.RightsRequests.Create(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create rights request", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRightsRequestPayload{
		RightsRequestEdge: types.NewRightsRequestEdge(rightsRequest, coredata.RightsRequestOrderFieldCreatedAt),
	}, nil
}

// UpdateRightsRequest is the resolver for the updateRightsRequest field.
func (r *mutationResolver) UpdateRightsRequest(ctx context.Context, input types.UpdateRightsRequestInput) (*types.UpdateRightsRequestPayload, error) {
	scope, err := r.authorize(ctx, input.ID, probo.ActionRightsRequestUpdate)
	if err != nil {
		return nil, err
	}

	req := probo.UpdateRightsRequestRequest{
		ID:           input.ID,
		RequestType:  input.RequestType,
		RequestState: input.RequestState,
		DataSubject:  gqlutils.UnwrapOmittable(input.DataSubject),
		Contact:      gqlutils.UnwrapOmittable(input.Contact),
		Details:      gqlutils.UnwrapOmittable(input.Details),
		Deadline:     gqlutils.UnwrapOmittable(input.Deadline),
		ActionTaken:  gqlutils.UnwrapOmittable(input.ActionTaken),
	}

	rightsRequest, err := r.probo.RightsRequests.Update(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update rights request", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRightsRequestPayload{
		RightsRequest: types.NewRightsRequest(rightsRequest),
	}, nil
}

// DeleteRightsRequest is the resolver for the deleteRightsRequest field.
func (r *mutationResolver) DeleteRightsRequest(ctx context.Context, input types.DeleteRightsRequestInput) (*types.DeleteRightsRequestPayload, error) {
	scope, err := r.authorize(ctx, input.RightsRequestID, probo.ActionRightsRequestDelete)
	if err != nil {
		return nil, err
	}

	if err := r.probo.RightsRequests.Delete(ctx, scope, input.RightsRequestID); err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete rights request", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRightsRequestPayload{
		DeletedRightsRequestID: input.RightsRequestID,
	}, nil
}

// Organization is the resolver for the organization field.
func (r *rightsRequestResolver) Organization(ctx context.Context, obj *types.RightsRequest) (*types.Organization, error) {
	scope, err := r.authorize(ctx, obj.ID, iam.ActionOrganizationGet)
	if err != nil {
		return nil, err
	}

	rightsRequest, err := r.probo.RightsRequests.Get(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get rights request", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	organization, err := r.probo.Organizations.Get(ctx, scope, rightsRequest.OrganizationID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Permission is the resolver for the permission field.
func (r *rightsRequestResolver) Permission(ctx context.Context, obj *types.RightsRequest, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *rightsRequestConnectionResolver) TotalCount(ctx context.Context, obj *types.RightsRequestConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionRightsRequestList)
	if err != nil {
		return 0, err
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		filter := obj.Filters
		if filter == nil {
			filter = coredata.NewRightsRequestFilter()
		}

		count, err := r.probo.RightsRequests.CountByOrganizationID(ctx, scope, obj.ParentID, filter)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count rights requests", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	default:
		r.logger.ErrorCtx(ctx, "unsupported resolver type for RightsRequestConnection")
		return 0, gqlutils.Internal(ctx)
	}
}

// StateCounts is the resolver for the stateCounts field.
func (r *rightsRequestConnectionResolver) StateCounts(ctx context.Context, obj *types.RightsRequestConnection) ([]*types.RightsRequestStateCount, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionRightsRequestList)
	if err != nil {
		return nil, err
	}

	filter := obj.Filters
	if filter == nil {
		filter = coredata.NewRightsRequestFilter()
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		counts, err := r.probo.RightsRequests.CountByStateForOrganizationID(ctx, scope, obj.ParentID, filter.WithoutStates())
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count rights requests by state", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		states := coredata.RightsRequestStates()
		result := make([]*types.RightsRequestStateCount, 0, len(states))

		for _, state := range states {
			result = append(result, &types.RightsRequestStateCount{
				State: state,
				Count: counts[state],
			})
		}

		return result, nil
	default:
		r.logger.ErrorCtx(ctx, "unsupported resolver type for RightsRequestConnection")
		return nil, gqlutils.Internal(ctx)
	}
}

// RightsRequest returns schema.RightsRequestResolver implementation.
func (r *Resolver) RightsRequest() schema.RightsRequestResolver { return &rightsRequestResolver{r} }

// RightsRequestConnection returns schema.RightsRequestConnectionResolver implementation.
func (r *Resolver) RightsRequestConnection() schema.RightsRequestConnectionResolver {
	return &rightsRequestConnectionResolver{r}
}

type (
	rightsRequestResolver           struct{ *Resolver }
	rightsRequestConnectionResolver struct{ *Resolver }
)
